stages:
  - lint
  - typecheck
  - test
  - build
  - deploy

variables:
  VITE_API_URL: "https://api.example.com" # override with real in prod

default:
  image: node:18

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

lint:
  stage: lint
  script:
    - npm run lint

typecheck:
  stage: typecheck
  script:
    - npx tsc --noEmit

test:
  stage: test
  script:
    - npm run test:coverage
  artifacts:
    when: always
    reports:
      cobertura: coverage/cobertura-coverage.xml
    paths:
      - coverage/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - aws s3 sync dist/ s3://your-s3-bucket-name --delete
    - aws cloudfront create-invalidation --distribution-id YOUR_DIST_ID --paths "/*"
  only:
    - main
